import { useState } from "react";
import { Link, useRoute } from "wouter";
import { ArrowLeft, CheckCircle2, CircleAlert, FilePenLine, LockKeyhole, Pencil, RotateCcw, ShieldAlert } from "lucide-react";
import { toast } from "sonner";
import { BnsReviewPanel, ReviewBrief } from "@/components/BnsReviewPanel";
import CaseReadinessPanel from "@/components/CaseReadinessPanel";
import CaseStatusTimeline from "@/components/CaseStatusTimeline";
import ComplaintStatusPill from "@/components/ComplaintStatusPill";
import FirSaathiShell from "@/components/FirSaathiShell";
import OfficerAccessGate, { useOfficerAccess } from "@/components/OfficerAccessGate";
import RecordLoading from "@/components/RecordLoading";
import ReviewerTranslationAid from "@/components/ReviewerTranslationAid";
import TranscriptSegmentReview from "@/components/TranscriptSegmentReview";
import { useOfficerWorkspaceTheme } from "@/hooks/useOfficerWorkspaceTheme";
import { trpc } from "@/lib/trpc";

const languageLabel = { en: "English", hi: "हिन्दी", gu: "ગુજરાતી", mr: "मराठी", bn: "বাংলা", ta: "தமிழ்", te: "తెలుగు", kn: "ಕನ್ನಡ", ml: "മലയാളം", pa: "ਪੰਜਾਬੀ" } as const;

export default function ComplaintReview() {
  const theme = useOfficerWorkspaceTheme();
  return <FirSaathiShell compact dark={theme.dark} officerTheme={theme}><OfficerAccessGate><ComplaintReviewContent dark={theme.dark} /></OfficerAccessGate></FirSaathiShell>;
}

function ComplaintReviewContent({ dark }: { dark: boolean }) {
  const [, params] = useRoute("/officer/:publicId");
  const publicId = params?.publicId ?? "";
  const { user } = useOfficerAccess();
  const detail = trpc.complaints.review.useQuery({ publicId }, { enabled: Boolean(publicId && user?.role !== "citizen") });
  const utils = trpc.useUtils();
  const [editingKey, setEditingKey] = useState<string | null>(null);
  const [editedValue, setEditedValue] = useState("");
  const [reason, setReason] = useState("");
  const [returnReason, setReturnReason] = useState("");
  const refresh = async () => { await utils.complaints.review.invalidate({ publicId }); await utils.complaints.list.invalidate(); };
  const correct = trpc.complaints.correctField.useMutation({ onSuccess: async () => { await refresh(); setEditingKey(null); setReason(""); toast.success("Correction recorded and returned to unverified."); }, onError: (error) => toast.error(error.message) });
  const returned = trpc.complaints.returnForCorrection.useMutation({ onSuccess: async () => { await refresh(); setReturnReason(""); toast.success("Clarification request sent with the documented reason."); }, onError: (error) => toast.error(error.message) });
  const verify = trpc.complaints.verify.useMutation({ onSuccess: async () => { await refresh(); toast.success("Record verified by the constable workspace. No FIR was registered."); }, onError: (error) => toast.error(error.message) });
  const translation = trpc.complaints.reviewerTranslation.useMutation({ onError: (error) => toast.error(error.message) });
  const page = dark ? "min-h-[calc(100vh-144px)] bg-[#081626] text-slate-100" : "app-real-surface min-h-[calc(100vh-144px)] text-[#102643]";
  const card = dark ? "border-white/10 bg-white/[0.055] text-slate-100" : "border-[#102643]/10 bg-white text-[#102643]";
  const muted = dark ? "text-slate-400" : "text-slate-600";

  if (detail.isLoading) return <RecordLoading label="Opening the constable review record" dark={dark} />;
  if (!detail.data) return <main className={`${page} grid place-items-center px-5`}><div className={`max-w-md rounded-2xl border p-7 text-center ${card}`}><CircleAlert className="mx-auto h-8 w-8 text-[#f48a51]" /><h1 className="mt-4 text-2xl font-bold">This review record is unavailable.</h1><p className={`mt-2 text-sm leading-6 ${muted}`}>{detail.error?.message || "The record may have been removed or you may not have access to it."}</p><Link href="/officer" className="focus-ring mt-6 inline-flex rounded-xl bg-[#102643] px-4 py-3 text-sm font-bold text-white">Return to review desk</Link></div></main>;

  const { complaint, fields, evidence, audit } = detail.data;
  if (complaint.status === "withdrawn") return <main className={`${page} py-8 sm:py-10`}><div className="mx-auto max-w-3xl px-5 sm:px-8"><Link href="/officer" className={`focus-ring inline-flex items-center gap-2 rounded-lg text-sm font-bold ${dark ? "text-slate-300 hover:text-white" : "text-slate-600 hover:text-[#102643]"}`}><ArrowLeft className="h-4 w-4" /> Review desk</Link><section className={`mt-5 rounded-2xl border p-7 text-center shadow-[0_14px_35px_rgba(12,32,57,.05)] ${card}`}><CircleAlert className="mx-auto h-9 w-9 text-rose-600" /><div className="mt-4 flex flex-wrap justify-center gap-3"><p className="text-xs font-bold uppercase tracking-[0.16em] text-rose-700">Withdrawn prototype record · {complaint.publicId}</p><ComplaintStatusPill status={complaint.status} /></div><h1 className="mt-3 text-3xl font-bold tracking-[-0.045em]">No review action is available.</h1><p className={`mx-auto mt-3 max-w-xl text-sm leading-6 ${muted}`}>The citizen withdrew this active prototype record. Its complaint content has been removed from normal workspaces, and no correction, return, verification, translation, or BNS action can be performed here.</p><p className={`mx-auto mt-3 max-w-xl text-xs leading-5 ${muted}`}>This tombstone supports accountability for the withdrawal event only; it does not indicate a real FIR withdrawal or a legal retention decision.</p></section></div></main>;
  const draft = complaint.draftJson;
  const sourceFields = fields.filter((field) => field.source !== "citizen_context");
  const additions = fields.filter((field) => field.source === "citizen_context");
  const transcriptSegments = evidence.flatMap((item) => item.encryptionMetadata?.transcriptSegments ?? []);
  const canVerify = complaint.status === "ready_for_review";

  return <main className={`${page} py-8 sm:py-10`}><div className="mx-auto max-w-7xl px-5 sm:px-8"><header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><Link href="/officer" className={`focus-ring inline-flex items-center gap-2 rounded-lg text-sm font-bold ${dark ? "text-slate-300 hover:text-white" : "text-slate-600 hover:text-[#102643]"}`}><ArrowLeft className="h-4 w-4" /> Review desk</Link><div className="mt-4 flex flex-wrap items-center gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#f48a51]">Constable review · {complaint.publicId}</p><h1 className="mt-1 text-3xl font-bold tracking-[-0.045em]">Verify the source, then decide.</h1></div><ComplaintStatusPill status={complaint.status} /></div></div><p className={`rounded-xl border px-3 py-2 text-xs font-bold ${dark ? "border-[#f48a51]/25 bg-[#c64e19]/10 text-[#ffd5c0]" : "border-[#c64e19]/20 bg-[#fff5ef] text-[#9b3a0d]"}`}><ShieldAlert className="mr-1.5 inline h-3.5 w-3.5" /> Verification is not FIR registration.</p></header>
    <div className="mt-7 grid gap-5 xl:grid-cols-[minmax(0,1.15fr)_minmax(360px,.85fr)]"><div className="space-y-5"><section className={`rounded-2xl border p-5 shadow-[0_14px_35px_rgba(12,32,57,.05)] ${card}`}><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-500">Lane 1 · immutable source record</p><p className="mt-1 text-sm font-bold">Selected language: {languageLabel[complaint.language]}</p></div><span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-50 px-2.5 py-1 text-[11px] font-bold text-emerald-800"><LockKeyhole className="h-3.5 w-3.5" /> Source preserved</span></div><blockquote lang={complaint.language} className={`mt-5 border-l-2 border-[#f48a51] pl-4 text-base leading-8 ${dark ? "text-slate-100" : "text-[#102643]"}`}>{complaint.sourceTranscript}</blockquote></section><TranscriptSegmentReview segments={transcriptSegments} dark={dark} title="Source transcript timecodes" />
      <section className={`rounded-2xl border p-5 ${card}`}><div className="flex items-center gap-2"><FilePenLine className="h-4 w-4 text-[#f48a51]" /><p className="text-xs font-bold uppercase tracking-[0.15em]">Lane 2 · citizen additions</p></div><p className={`mt-2 text-xs leading-5 ${muted}`}>These notes are kept separate from the immutable source transcript.</p>{additions.length ? <ul className="mt-4 space-y-2">{additions.map((field) => <li key={field.id} className={`rounded-xl p-3 text-sm leading-6 ${dark ? "bg-black/15" : "bg-[#f5f2eb]"}`}><b>{field.label}:</b> {field.value}</li>)}</ul> : <p className={`mt-4 rounded-xl p-3 text-sm ${dark ? "bg-black/15 text-slate-400" : "bg-[#f5f2eb] text-slate-600"}`}>No separately supplied context or correction note.</p>}</section><CaseStatusTimeline status={complaint.status} audit={audit} /><CaseReadinessPanel fields={fields} audit={audit} draft={draft} evidenceCount={evidence.length} status={complaint.status} dark={dark} />
      <section className={`rounded-2xl border p-5 ${card}`}><div className="flex items-center gap-2"><Pencil className="h-4 w-4 text-[#f48a51]" /><p className="text-xs font-bold uppercase tracking-[0.15em]">Working-field corrections</p></div><div className="mt-4 space-y-3">{sourceFields.map((field) => <div key={field.id} className={`rounded-xl border p-3 ${dark ? "border-white/10 bg-black/15" : "border-[#102643]/10 bg-[#fbfaf6]"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1"><p className="text-sm font-bold">{field.label}</p>{editingKey === field.fieldKey ? <div className="mt-3 space-y-2"><input value={editedValue} onChange={(event) => setEditedValue(event.target.value)} className={`focus-ring h-10 w-full rounded-lg border px-3 text-sm ${dark ? "border-white/10 bg-[#102643] text-white" : "border-[#102643]/15 bg-white"}`} /><input value={reason} onChange={(event) => setReason(event.target.value)} className={`focus-ring h-10 w-full rounded-lg border px-3 text-sm ${dark ? "border-white/10 bg-[#102643] text-white" : "border-[#102643]/15 bg-white"}`} placeholder="Reason for correction (required)" /><div className="flex gap-2"><button type="button" disabled={!editedValue.trim() || reason.trim().length < 4 || correct.isPending} onClick={() => correct.mutate({ publicId, fieldKey: field.fieldKey, label: field.label, value: editedValue, reason })} className="focus-ring rounded-lg bg-[#102643] px-3 py-2 text-xs font-bold text-white disabled:opacity-50">Save correction</button><button type="button" onClick={() => { setEditingKey(null); setReason(""); }} className={`focus-ring rounded-lg px-3 py-2 text-xs font-bold ${muted}`}>Cancel</button></div></div> : <p className={`mt-1 text-sm leading-6 ${muted}`}>{field.value}</p>}</div>{editingKey !== field.fieldKey && <button type="button" onClick={() => { setEditingKey(field.fieldKey); setEditedValue(field.value); setReason(""); }} className="focus-ring inline-flex h-9 items-center gap-1.5 rounded-lg border border-[#102643]/12 px-3 text-xs font-bold"><Pencil className="h-3.5 w-3.5" /> Correct</button>}</div></div>)}</div></section></div>
      <aside className="space-y-5"><ReviewerTranslationAid translation={translation.data} pending={translation.isPending} onGenerate={() => translation.mutate({ publicId })} dark={dark} /><ReviewBrief sourceTranscript={complaint.sourceTranscript} fields={fields} draft={draft} dark={dark} /><BnsReviewPanel suggestions={draft.bnsSuggestions} /><section className={`rounded-2xl border p-5 ${dark ? "border-[#f48a51]/25 bg-[#c64e19]/10" : "border-[#c64e19]/20 bg-[#fff5ef]"}`}><p className={`text-xs font-bold uppercase tracking-[0.15em] ${dark ? "text-[#ffd5c0]" : "text-[#9b3a0d]"}`}>Lane 4 · constable decision</p><p className={`mt-2 text-xs leading-5 ${dark ? "text-[#ffd5c0]" : "text-[#7e3b1f]"}`}>Review the original, separate additions, uncertainty cues, and non-authoritative aids before acting.</p><div className="mt-4 space-y-3"><label className={`block text-xs font-semibold ${dark ? "text-[#ffd5c0]" : "text-[#7e3b1f]"}`}>Return for clarification<textarea value={returnReason} onChange={(event) => setReturnReason(event.target.value)} rows={3} className={`focus-ring mt-1.5 w-full resize-y rounded-lg border p-2.5 text-sm ${dark ? "border-white/15 bg-[#102643] text-white" : "border-[#c64e19]/25 bg-white text-[#102643]"}`} placeholder="Document the missing information or concern" /></label><button type="button" disabled={returnReason.trim().length < 4 || returned.isPending} onClick={() => returned.mutate({ publicId, reason: returnReason })} className="focus-ring inline-flex w-full items-center justify-center gap-2 rounded-lg border border-[#c64e19]/35 bg-white px-3 py-2.5 text-xs font-bold text-[#9b3a0d] disabled:opacity-50"><RotateCcw className="h-3.5 w-3.5" /> Return with reason</button><button type="button" disabled={!canVerify || verify.isPending} onClick={() => verify.mutate({ publicId })} className="focus-ring inline-flex w-full items-center justify-center gap-2 rounded-lg bg-[#102643] px-3 py-2.5 text-xs font-bold text-white disabled:opacity-50"><CheckCircle2 className="h-3.5 w-3.5" /> Verify prototype record</button>{!canVerify && <p className={`text-[11px] leading-5 ${dark ? "text-[#ffd5c0]" : "text-[#8f360e]"}`}>Verification is available only after citizen confirmation and review readiness.</p>}</div></section></aside></div></div></main>;
}
