import { useEffect, useState } from "react";
import { Link } from "wouter";
import { ArrowLeft, BadgeCheck, BrainCircuit, Check, CirclePlay, FileCheck2, Gauge, Languages, LockKeyhole, Pause, RefreshCw, ShieldCheck, Sparkles, UserRoundCheck } from "lucide-react";
import AnimatedWaveform from "@/components/AnimatedWaveform";
import FirSaathiShell from "@/components/FirSaathiShell";

const scenarios = {
  gu: { label: "ગુજરાતી", statement: "મને ગઈકાલે સાંજે રસ્તા પર બે લોકોએ રોકી મારી ચેન લઈ લીધી. નજીકમાં દુકાનદાર હતા.", signal: "Property mentioned: chain", followUp: "ઘટના લગભગ કેટલા વાગ્યે બની હતી?" },
  hi: { label: "हिन्दी", statement: "मुझे कल शाम रास्ते में दो लोगों ने रोका और मेरी चेन ले ली। पास में दुकानदार थे।", signal: "Property mentioned: chain", followUp: "घटना लगभग कितने बजे हुई थी?" },
  en: { label: "English", statement: "Two people stopped me on the road yesterday evening and took my chain. Shopkeepers were nearby.", signal: "Property mentioned: chain", followUp: "At approximately what time did this happen?" },
} as const;

const stages = ["Citizen speaks", "AI structures", "Citizen confirms", "Constable verifies"];

export default function ImpactDemo() {
  const [language, setLanguage] = useState<keyof typeof scenarios>("gu");
  const [stage, setStage] = useState(0);
  const [playing, setPlaying] = useState(false);
  const sample = scenarios[language];

  useEffect(() => {
    if (!playing) return;
    const timer = window.setTimeout(() => {
      setStage((current) => {
        if (current >= stages.length - 1) { setPlaying(false); return current; }
        return current + 1;
      });
    }, 1750);
    return () => window.clearTimeout(timer);
  }, [playing, stage]);

  const reset = () => { setPlaying(false); setStage(0); };
  const start = () => { if (stage >= stages.length - 1) setStage(0); setPlaying(true); };

  return <FirSaathiShell dark compact><main className="min-h-[calc(100vh-144px)] navy-surface py-8 sm:py-10"><div className="mx-auto max-w-6xl px-5 sm:px-8"><Link href="/" className="focus-ring inline-flex items-center gap-2 rounded-lg text-sm font-bold text-slate-300 hover:text-white"><ArrowLeft className="h-4 w-4" /> Back to overview</Link><div className="mt-6 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="inline-flex items-center gap-2 rounded-full border border-[#f7b28c]/25 bg-[#c64e19]/15 px-3 py-1.5 text-[11px] font-bold uppercase tracking-[0.15em] text-[#ffd5c0]"><Sparkles className="h-3.5 w-3.5" /> Impact Fest guided demo</p><h1 className="mt-4 max-w-2xl text-4xl font-bold tracking-[-0.05em] text-white sm:text-5xl">A complaint journey where AI never replaces the citizen.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">A self-contained showcase state. It demonstrates the safety model even when live audio, Groq, or data services are unavailable.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={start} className="pressable focus-ring inline-flex items-center gap-2 rounded-xl bg-[#c64e19] px-4 py-3 text-sm font-bold text-white">{playing ? <Pause className="h-4 w-4" /> : <CirclePlay className="h-4 w-4" />}{playing ? "Demo playing" : "Run 30-second story"}</button><button type="button" onClick={reset} className="pressable focus-ring inline-flex items-center gap-2 rounded-xl border border-white/15 bg-white/[0.07] px-4 py-3 text-sm font-bold text-white"><RefreshCw className="h-4 w-4" /> Reset</button></div></div>
      <div className="mt-8 grid gap-3 rounded-2xl border border-white/10 bg-white/[0.05] p-3 sm:grid-cols-4">{stages.map((item, index) => <button key={item} type="button" onClick={() => { setPlaying(false); setStage(index); }} className={`focus-ring flex items-center gap-3 rounded-xl p-3 text-left ${index === stage ? "bg-white text-[#102643]" : index < stage ? "bg-[#6ed6c5]/15 text-[#c4fff6]" : "text-slate-400"}`}><span className={`grid h-6 w-6 place-items-center rounded-full text-[11px] font-bold ${index <= stage ? "bg-[#c64e19] text-white" : "border border-white/20"}`}>{index < stage ? <Check className="h-3.5 w-3.5" /> : index + 1}</span><span className="text-xs font-bold">{item}</span></button>)}</div>
      <div className="mt-5 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><section className="overflow-hidden rounded-[1.4rem] border border-white/12 bg-[#071525]/70 shadow-[0_28px_70px_rgba(0,0,0,.3)]"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 px-5 py-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">Citizen layer · source stays intact</p><p className="mt-1 text-sm font-bold text-white">Select the language of the source statement</p></div><div className="flex rounded-lg bg-white/[0.08] p-1">{(Object.keys(scenarios) as Array<keyof typeof scenarios>).map((key) => <button key={key} type="button" onClick={() => setLanguage(key)} className={`focus-ring rounded-md px-2.5 py-1.5 text-xs font-bold ${language === key ? "bg-white text-[#102643]" : "text-slate-300"}`}>{scenarios[key].label}</button>)}</div></div><div className="p-5 sm:p-6"><div className="flex items-center gap-3"><span className={`grid h-10 w-10 place-items-center rounded-full ${stage === 0 || playing ? "bg-[#c64e19]" : "bg-[#19344e]"} text-white`}><Languages className="h-5 w-5" /></span><div><p className="text-sm font-bold text-white">{stage === 0 ? "Live source statement" : "Source statement preserved"}</p><p className="text-xs text-slate-400">No translation. No legal formalisation. No invented detail.</p></div></div><blockquote lang={language} className="mt-6 border-l-2 border-[#f48a51] pl-4 text-lg leading-8 text-white">{sample.statement}</blockquote><AnimatedWaveform active={stage === 0 || playing} className="mt-7" label="Live citizen audio waveform" /><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-white/10 bg-white/[0.055] p-4"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-500">Visible AI guardrail</p><p className="mt-2 text-sm font-bold text-[#c4fff6]"><LockKeyhole className="mr-1.5 inline h-4 w-4" /> Only exact excerpts become fields</p></div><div className={`rounded-xl border p-4 ${stage >= 2 ? "border-[#6ed6c5]/35 bg-[#6ed6c5]/10" : "border-white/10 bg-white/[0.055]"}`}><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-500">Citizen checkpoint</p><p className="mt-2 text-sm font-bold text-white">{stage >= 2 ? "Read-back acknowledged" : "Read-back required"}</p></div></div></div></section>
        <section className="rounded-[1.4rem] border border-white/12 bg-white/[0.06] p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#f48a51]">Explainable AI layer</p><h2 className="mt-1 text-xl font-bold tracking-[-0.03em] text-white">See what the assistant may—and may not—do.</h2></div><BrainCircuit className={`h-6 w-6 ${stage >= 1 ? "text-[#6ed6c5]" : "text-slate-500"}`} /></div><div className="mt-6 space-y-3"><div className={`rounded-xl border p-4 transition-colors ${stage >= 1 ? "border-[#6ed6c5]/35 bg-[#6ed6c5]/10" : "border-white/10 bg-white/[0.04]"}`}><div className="flex items-center justify-between"><p className="text-xs font-bold text-white">Extract only sourced signals</p>{stage >= 1 && <BadgeCheck className="h-4 w-4 text-[#6ed6c5]" />}</div><p className="mt-2 text-sm text-slate-300">{stage >= 1 ? sample.signal : "Waiting for a statement…"}</p></div><div className={`rounded-xl border p-4 transition-colors ${stage >= 1 ? "border-[#f48a51]/35 bg-[#c64e19]/10" : "border-white/10 bg-white/[0.04]"}`}><p className="text-xs font-bold text-white">Ask, do not assume</p><p className="mt-2 text-sm text-slate-300">{stage >= 1 ? sample.followUp : "A concise missing-detail question will appear here."}</p></div><div className={`rounded-xl border p-4 transition-colors ${stage >= 3 ? "border-[#6ed6c5]/35 bg-[#6ed6c5]/10" : "border-white/10 bg-white/[0.04]"}`}><p className="text-xs font-bold text-white">Human verification remains</p><p className="mt-2 text-sm text-slate-300">{stage >= 3 ? "Constable reviews the source, corrections, audit trail, and demonstrative reference before verification." : "No AI output registers an FIR or decides a legal section."}</p></div></div><div className="mt-6 rounded-xl border border-[#f48a51]/25 bg-[#fff5ef] p-4 text-[#8f360e]"><div className="flex gap-2"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0" /><p className="text-xs leading-5"><b>Impact principle:</b> the citizen’s words remain visible at every stage; AI makes missing information and uncertainty easier to see.</p></div></div></section></div>
      <section className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-white/10 bg-white/[0.055] p-4 text-white"><Gauge className="h-5 w-5 text-[#f48a51]" /><p className="mt-4 text-2xl font-bold">3</p><p className="mt-1 text-xs font-semibold text-slate-400">explicit language choices</p></div><div className="rounded-xl border border-white/10 bg-white/[0.055] p-4 text-white"><UserRoundCheck className="h-5 w-5 text-[#6ed6c5]" /><p className="mt-4 text-2xl font-bold">2</p><p className="mt-1 text-xs font-semibold text-slate-400">human checkpoints</p></div><div className="rounded-xl border border-white/10 bg-white/[0.055] p-4 text-white"><FileCheck2 className="h-5 w-5 text-[#f48a51]" /><p className="mt-4 text-2xl font-bold">0</p><p className="mt-1 text-xs font-semibold text-slate-400">silent source rewrites</p></div></section></div></main></FirSaathiShell>;
}
