import { BadgeCheck, CheckCircle2, ChevronRight, CircleAlert, Clock3, FileAudio, FilePenLine, Filter, Loader2, Search, ShieldAlert, UsersRound } from "lucide-react";
import { Link } from "wouter";
import FirSaathiShell from "@/components/FirSaathiShell";
import ComplaintStatusPill from "@/components/ComplaintStatusPill";
import { trpc } from "@/lib/trpc";

const languageLabels = { en: "English", hi: "हिन्दी", gu: "ગુજરાતી" } as const;

function titleFor(source: string) { return source.length > 54 ? `${source.slice(0, 54)}…` : source; }

export default function OfficerQueue() {
  const queue = trpc.complaints.list.useQuery();
  const open = queue.data?.filter((item) => item.status !== "verified") ?? [];
  const returned = queue.data?.filter((item) => item.status === "returned").length ?? 0;
  const verified = queue.data?.filter((item) => item.status === "verified").length ?? 0;
  return (
    <FirSaathiShell compact>
      <main className="min-h-[calc(100vh-144px)] bg-[#f4f2ec] py-8 sm:py-10">
        <div className="mx-auto max-w-6xl px-5 sm:px-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#c64e19]">Constable workspace</p><h1 className="mt-2 text-3xl font-bold tracking-[-0.045em] text-[#102643]">Review desk</h1><p className="mt-2 max-w-xl text-sm leading-6 text-slate-600">Inspect the source transcript, correct with a recorded reason, and verify the prototype record. Do not register an FIR here.</p></div><div className="inline-flex items-center gap-2 rounded-full border border-[#c64e19]/25 bg-[#fff5ef] px-3 py-2 text-xs font-bold text-[#a83d10]"><ShieldAlert className="h-3.5 w-3.5" /> Demonstration workspace</div></div>
          <div className="mt-7 grid gap-5 lg:grid-cols-[minmax(0,1fr)_300px]"><section className="overflow-hidden rounded-[1.25rem] border border-[#102643]/10 bg-white shadow-[0_18px_42px_rgba(12,32,57,.07)]"><div className="flex flex-col gap-3 border-b border-[#102643]/10 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input aria-label="Search demo complaints" className="focus-ring h-10 w-full rounded-xl border border-[#102643]/12 bg-[#fbfaf6] pl-9 pr-3 text-sm sm:w-72" placeholder="Search draft records" /></div><button className="focus-ring inline-flex h-10 items-center justify-center gap-2 rounded-xl border border-[#102643]/12 px-3 text-sm font-bold text-slate-600 hover:bg-[#f8f5ef]"><Filter className="h-4 w-4" /> Filter</button></div><div className="divide-y divide-[#102643]/8">{queue.isLoading ? <div className="grid min-h-48 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-[#c64e19]" /></div> : queue.isError ? <div className="p-6 text-sm text-[#9b3a0d]">{queue.error.message}</div> : open.map((item) => <article key={item.id} className="group flex flex-col gap-4 px-5 py-5 transition-colors hover:bg-[#fdfbf7] sm:flex-row sm:items-center"><span className={`h-2.5 w-2.5 shrink-0 rounded-full ${item.status === "returned" ? "bg-slate-500" : item.status === "needs_citizen_confirmation" ? "bg-amber-500" : "bg-[#c64e19]"}`} aria-label={item.status} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-x-2 gap-y-1"><span className="text-xs font-bold text-slate-500">{item.publicId}</span><span className="text-xs font-medium text-slate-500">{languageLabels[item.language]}</span></div><h2 className="mt-1 truncate text-base font-bold tracking-[-0.015em] text-[#102643]">{titleFor(item.sourceTranscript)}</h2><p className="mt-1 flex items-center gap-1.5 text-xs text-slate-500"><Clock3 className="h-3.5 w-3.5" /> {new Date(item.updatedAt).toLocaleString()}</p></div><ComplaintStatusPill status={item.status} /><Link href={`/officer/${item.publicId}`} className="focus-ring inline-flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border border-[#102643]/10 text-[#102643] hover:bg-[#102643] hover:text-white" aria-label={`Open ${item.publicId}`}><ChevronRight className="h-4 w-4" /></Link></article>)}</div></section>
            <aside className="space-y-4"><section className="rounded-2xl bg-[#102643] p-5 text-white"><div className="flex items-center gap-2"><UsersRound className="h-4 w-4 text-[#f48a51]" /><p className="text-xs font-bold uppercase tracking-[0.15em] text-slate-300">Today’s demo queue</p></div><div className="mt-5 grid grid-cols-3 divide-x divide-white/10"><div><p className="text-2xl font-bold">{open.length.toString().padStart(2, "0")}</p><p className="mt-1 text-[10px] uppercase tracking-[0.12em] text-slate-400">Open</p></div><div className="pl-4"><p className="text-2xl font-bold">{returned.toString().padStart(2, "0")}</p><p className="mt-1 text-[10px] uppercase tracking-[0.12em] text-slate-400">Returned</p></div><div className="pl-4"><p className="text-2xl font-bold">{verified.toString().padStart(2, "0")}</p><p className="mt-1 text-[10px] uppercase tracking-[0.12em] text-slate-400">Verified</p></div></div></section><section className="rounded-2xl border border-[#102643]/10 bg-white p-5"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#c64e19]">Verification reminder</p><ul className="mt-4 space-y-3 text-xs leading-5 text-slate-600"><li className="flex gap-2"><FileAudio className="h-4 w-4 shrink-0 text-[#102643]" />Compare the source transcript and audio metadata.</li><li className="flex gap-2"><FilePenLine className="h-4 w-4 shrink-0 text-[#102643]" />Record why every correction was made.</li><li className="flex gap-2"><BadgeCheck className="h-4 w-4 shrink-0 text-[#102643]" />Verify only after checking unresolved details.</li></ul></section><section className="rounded-2xl border border-[#c64e19]/20 bg-[#fff5ef] p-5"><div className="flex gap-2"><CircleAlert className="h-4 w-4 shrink-0 text-[#c64e19]" /><p className="text-xs leading-5 text-[#8f360e]">BNS suggestions are demonstrative and non-authoritative. Use the safe REVIEW outcome where no listed reference fits.</p></div></section></aside>
          </div><div className="mt-5 flex items-center gap-2 text-xs text-slate-500"><CheckCircle2 className="h-3.5 w-3.5 text-[#15803d]" /> The office review route will preserve all prior values, actor labels, timestamps, and verification states.</div></div>
      </main>
    </FirSaathiShell>
  );
}
