import { ArrowRight, AudioLines, BadgeCheck, CheckCircle2, CircleHelp, FileCheck2, Languages, LockKeyhole, Mic, ScanSearch, ShieldCheck, UserRoundCheck, Waves } from "lucide-react";
import React, { useLayoutEffect, useRef } from "react";
import { Link } from "wouter";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import FirSaathiShell from "@/components/FirSaathiShell";

gsap.registerPlugin(ScrollTrigger);

export const processSteps = [
  { number: "01", title: "Choose the language", eyebrow: "Citizen decides", copy: "The citizen picks a language before recording or typing. The system does not guess from a short voice clip.", ai: "Shows language options", human: "Chooses the language", icon: Languages, visual: "language" },
  { number: "02", title: "Share what happened", eyebrow: "Source begins", copy: "The citizen records a voice statement or types it directly. The original wording becomes the source record.", ai: "Captures the audio safely", human: "Tells the story in their words", icon: Mic, visual: "wave" },
  { number: "03", title: "Keep the source separate", eyebrow: "Source protected", copy: "Transcript, corrections, and added context remain visibly distinct so nothing is silently rewritten.", ai: "Labels source and additions", human: "Can correct the transcript", icon: LockKeyhole, visual: "source" },
  { number: "04", title: "Make only gaps visible", eyebrow: "AI assists", copy: "The assistant looks for material details already present, then asks one optional question only when a useful gap remains.", ai: "Surfaces uncertainty", human: "Skips or adds context", icon: ScanSearch, visual: "question" },
  { number: "05", title: "Read back and confirm", eyebrow: "Citizen checkpoint", copy: "The citizen checks the source statement and any separate context before the record is sent for review.", ai: "Prepares a readable review", human: "Confirms what is shared", icon: FileCheck2, visual: "confirm" },
  { number: "06", title: "A constable verifies", eyebrow: "Human decision", copy: "An assigned constable reviews the source, corrections, evidence metadata, and visible uncertainty before making any verification decision.", ai: "Shows source-backed aids", human: "Reviews, corrects, and verifies", icon: UserRoundCheck, visual: "verify" },
] as const;

function StepVisual({ type }: { type: (typeof processSteps)[number]["visual"] }) {
  if (type === "language") return <div className="process-mini-grid" aria-hidden="true"><span>EN</span><span>हि</span><span>ગુ</span><span>த</span></div>;
  if (type === "wave") return <div className="process-wave" aria-hidden="true">{[18, 32, 48, 25, 58, 37, 21, 44, 29, 52, 20].map((height, index) => <i key={index} style={{ height }} />)}</div>;
  if (type === "source") return <div className="process-source-card" aria-hidden="true"><span className="process-lock-dot"><LockKeyhole /></span><div><b>Source transcript</b><i /><i className="short" /></div></div>;
  if (type === "question") return <div className="process-question-card" aria-hidden="true"><CircleHelp /><div><span>One optional detail</span><b>When did this happen?</b></div></div>;
  if (type === "confirm") return <div className="process-confirm-card" aria-hidden="true"><span><CheckCircle2 /> Read back</span><span><CheckCircle2 /> Citizen check</span></div>;
  return <div className="process-verify-card" aria-hidden="true"><ShieldCheck /><div><b>Human review</b><span>Decision stays with constable</span></div><BadgeCheck /></div>;
}

export default function ProcessStory() {
  const pageRef = useRef<HTMLElement | null>(null);

  useLayoutEffect(() => {
    if (!pageRef.current || window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    const ctx = gsap.context(() => {
      gsap.from(".process-hero-copy > *", { y: 24, opacity: 0, duration: 0.62, ease: "power3.out", stagger: 0.075, clearProps: "transform,opacity" });
      gsap.from(".process-console", { y: 26, scale: 0.97, opacity: 0, duration: 0.78, delay: 0.12, ease: "power4.out", clearProps: "transform,opacity" });
      gsap.to(".process-orbit", { rotate: 360, transformOrigin: "50% 50%", duration: 22, ease: "none", repeat: -1 });
      gsap.utils.toArray<HTMLElement>(".process-step").forEach((step) => {
        gsap.from(step, { y: 34, opacity: 0, duration: 0.58, ease: "power3.out", scrollTrigger: { trigger: step, start: "top 86%", once: true }, clearProps: "transform,opacity" });
      });
    }, pageRef);
    return () => ctx.revert();
  }, []);

  return (
    <FirSaathiShell dark showcase>
      <main ref={pageRef} className="process-story overflow-hidden bg-[#071525] text-white">
        <section className="navy-surface process-hero relative overflow-hidden border-b border-white/10">
          <div className="absolute inset-0 opacity-[0.13] [background-image:linear-gradient(rgba(255,255,255,.25)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.25)_1px,transparent_1px)] [background-size:46px_46px]" aria-hidden="true" />
          <div className="absolute left-1/2 top-1/2 h-[34rem] w-[34rem] -translate-x-1/2 -translate-y-1/2 rounded-full border border-[#f48a51]/15" aria-hidden="true" />
          <div className="relative mx-auto grid max-w-7xl gap-12 px-5 py-16 sm:px-8 lg:grid-cols-[1fr_.92fr] lg:items-center lg:gap-20 lg:py-24">
            <div className="process-hero-copy max-w-3xl">
              <span className="inline-flex items-center gap-2 rounded-full border border-[#f7b28c]/25 bg-[#c64e19]/15 px-3 py-1.5 text-xs font-bold uppercase tracking-[0.16em] text-[#ffd5c0]"><Waves className="h-3.5 w-3.5" /> Complete process</span>
              <h1 className="mt-6 text-5xl font-bold tracking-[-0.06em] text-white sm:text-6xl lg:text-7xl">Every word takes a <span className="text-[#f48a51]">visible path.</span></h1>
              <p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300 sm:text-xl">From a citizen’s chosen language to a constable’s final review, FIR Saathi keeps the source, the uncertainty, and every human checkpoint visible.</p>
              <div className="mt-8 flex flex-wrap gap-3 text-xs font-bold text-slate-200"><span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.055] px-3 py-2"><AudioLines className="h-4 w-4 text-[#6ed6c5]" /> Voice or type</span><span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.055] px-3 py-2"><LockKeyhole className="h-4 w-4 text-[#f48a51]" /> Source preserved</span><span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.055] px-3 py-2"><UserRoundCheck className="h-4 w-4 text-[#f48a51]" /> Human verified</span></div>
              <div className="mt-10 flex flex-col gap-3 sm:flex-row"><a href="#journey" className="pressable focus-ring inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#c64e19] px-5 text-sm font-bold text-white shadow-[0_13px_35px_rgba(198,78,25,.28)] hover:bg-[#da5b22]">Follow the journey <ArrowRight className="h-4 w-4" /></a><Link href="/intake" className="pressable focus-ring inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-white/15 bg-white/[0.06] px-5 text-sm font-bold text-white hover:bg-white/[0.12]">Try the intake</Link></div>
              <p className="mt-6 flex items-start gap-2 text-xs leading-5 text-slate-400"><ShieldCheck className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[#6ed6c5]" /> This prototype drafts and verifies a review record; it does not register an FIR or provide emergency help.</p>
            </div>
            <div className="process-console relative rounded-[1.7rem] border border-white/12 bg-[#091a2d]/90 p-4 shadow-[0_30px_85px_rgba(0,0,0,.36)] backdrop-blur-xl sm:p-5">
              <div className="process-orbit absolute -right-10 -top-10 h-36 w-36 rounded-full border border-[#f48a51]/35" aria-hidden="true"><span className="absolute left-1/2 top-0 h-3 w-3 -translate-x-1/2 rounded-full bg-[#f48a51] shadow-[0_0_18px_#f48a51]" /></div>
              <div className="relative overflow-hidden rounded-[1.25rem] border border-white/10 bg-white/[0.045] p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-slate-400">Live process map</p><p className="mt-1 text-sm font-bold">Source → check → human review</p></div><span className="process-live-dot inline-flex items-center gap-1.5 rounded-full bg-[#6ed6c5]/15 px-2.5 py-1 text-[11px] font-bold text-[#c4fff6]"><i /> Guided</span></div><div className="process-route-line mt-7" aria-hidden="true"><span className="active" /><span /><span /><span /><span /><span /></div><div className="mt-4 grid grid-cols-3 gap-2 text-[10px] font-bold uppercase tracking-[0.1em] text-slate-400"><span>Citizen</span><span className="text-center">AI assist</span><span className="text-right">Constable</span></div><div className="mt-5 grid gap-3"><div className="rounded-xl border border-white/8 bg-white/[0.045] p-3"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#c64e19]/15 text-[#f4a77f]"><Mic className="h-4 w-4" /></span><div><p className="text-xs font-bold">Citizen statement</p><p className="mt-1 text-[11px] text-slate-400">Original wording stays intact</p></div><CheckCircle2 className="ml-auto h-4 w-4 text-[#6ed6c5]" /></div></div><div className="rounded-xl border border-[#f48a51]/25 bg-[#c64e19]/10 p-3"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#f48a51]/15 text-[#f4a77f]"><ScanSearch className="h-4 w-4" /></span><div><p className="text-xs font-bold">One optional question</p><p className="mt-1 text-[11px] text-slate-300">Only where a meaningful gap remains</p></div></div></div><div className="rounded-xl border border-[#6ed6c5]/25 bg-[#6ed6c5]/10 p-3"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#6ed6c5]/15 text-[#c4fff6]"><UserRoundCheck className="h-4 w-4" /></span><div><p className="text-xs font-bold">Human verification</p><p className="mt-1 text-[11px] text-slate-300">Constable retains final judgment</p></div></div></div></div></div>
            </div>
          </div>
        </section>

        <section id="journey" className="process-paper relative bg-[#f6f3ed] py-18 text-[#102643] sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#c64e19]">Six visible moments</p><h2 className="mt-4 text-4xl font-bold tracking-[-0.055em] sm:text-5xl">The process never asks a person to trust a black box.</h2><p className="mt-5 max-w-2xl text-base leading-7 text-slate-600">Each point in the journey makes clear what the assistant can support, what remains optional, and who is responsible for the next decision.</p></div><div className="process-timeline relative mt-14 grid gap-5 lg:grid-cols-2 lg:gap-x-16 lg:gap-y-8">{processSteps.map((step, index) => { const Icon = step.icon; return <article key={step.number} className={`process-step group relative rounded-[1.35rem] border border-[#102643]/10 bg-white/90 p-5 shadow-[0_18px_38px_rgba(12,32,57,.06)] sm:p-6 ${index % 2 === 1 ? "lg:translate-y-12" : ""}`}><div className="flex items-start justify-between gap-5"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#fce9df] text-[#c64e19]"><Icon className="h-5 w-5" /></span><span className="text-xs font-bold tracking-[0.17em] text-[#c64e19]">{step.number}</span></div><p className="mt-6 text-[10px] font-bold uppercase tracking-[0.17em] text-[#c64e19]">{step.eyebrow}</p><h3 className="mt-2 text-2xl font-bold tracking-[-0.035em]">{step.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{step.copy}</p><div className="mt-6"><StepVisual type={step.visual} /></div><div className="mt-6 grid gap-2 border-t border-[#102643]/8 pt-4 text-xs"><p className="flex gap-2 text-slate-600"><span className="font-bold text-[#c64e19]">AI supports</span><span>{step.ai}</span></p><p className="flex gap-2 text-[#102643]"><span className="font-bold text-[#15803d]">Person retains</span><span>{step.human}</span></p></div></article>; })}</div></div></section>

        <section className="bg-[#0a1a2e] px-5 py-18 sm:px-8 sm:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#f48a51]">Not a straight line</p><h2 className="mt-4 text-4xl font-bold tracking-[-0.05em] sm:text-5xl">Pause, return, correct, then continue.</h2><p className="mt-5 max-w-xl text-base leading-7 text-slate-300">A citizen can save an unfinished intake privately, recover it with a private resume code, and keep the source statement separate from later corrections or context.</p><div className="mt-8 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[0.055] p-5"><LockKeyhole className="h-5 w-5 text-[#f48a51]" /><h3 className="mt-4 text-base font-bold">Private continuation</h3><p className="mt-2 text-sm leading-6 text-slate-300">A private FSR code restores an unfinished intake; it is not a public case number.</p></div><div className="rounded-2xl border border-white/10 bg-white/[0.055] p-5"><FileCheck2 className="h-5 w-5 text-[#6ed6c5]" /><h3 className="mt-4 text-base font-bold">Visible correction trail</h3><p className="mt-2 text-sm leading-6 text-slate-300">Corrections and review reasons stay linked to the source instead of replacing it.</p></div></div></div><div className="process-loop-card relative rounded-[1.6rem] border border-white/10 bg-white/[0.05] p-6 sm:p-8"><div className="absolute inset-8 rounded-full border border-dashed border-[#6ed6c5]/25" aria-hidden="true" /><div className="relative grid aspect-square place-items-center"><div className="grid h-28 w-28 place-items-center rounded-full border border-[#f48a51]/30 bg-[#c64e19]/10 text-center"><span className="text-xs font-bold uppercase tracking-[0.15em] text-[#ffd5c0]">Citizen<br />in control</span></div><span className="process-loop-node top-node"><Mic /></span><span className="process-loop-node right-node"><ScanSearch /></span><span className="process-loop-node bottom-node"><FileCheck2 /></span><span className="process-loop-node left-node"><UserRoundCheck /></span></div></div></div></section>

        <section className="bg-[#f6f3ed] px-5 py-16 text-[#102643] sm:px-8"><div className="mx-auto flex max-w-6xl flex-col gap-7 rounded-[1.55rem] border border-[#102643]/10 bg-white p-7 shadow-[0_20px_45px_rgba(12,32,57,.07)] sm:p-10 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#c64e19]">Ready to see it in action?</p><h2 className="mt-3 text-3xl font-bold tracking-[-0.04em] sm:text-4xl">Start with the citizen’s own words.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">The live prototype begins by letting the citizen select a language and decide how to share their statement.</p></div><div className="flex flex-col gap-3 sm:flex-row"><Link href="/intake" className="pressable focus-ring inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#c64e19] px-5 text-sm font-bold text-white hover:bg-[#a83d10]">Open citizen intake <ArrowRight className="h-4 w-4" /></Link><Link href="/" className="pressable focus-ring inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-[#102643]/15 px-5 text-sm font-bold text-[#102643] hover:bg-[#f6f3ed]">Back to overview</Link></div></div></section>
      </main>
    </FirSaathiShell>
  );
}
