import { useMemo, useState } from "react";
import { Link } from "wouter";
import { CheckCircle2, KeyRound, Loader2 } from "lucide-react";
import { AuthFeedback } from "@/components/AuthFeedback";
import FirSaathiShell from "@/components/FirSaathiShell";
import { updatePasswordFromRecovery } from "@/lib/supabaseAuth";

export default function ResetPassword() {
  const [password, setPassword] = useState("");
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const token = useMemo(() => new URLSearchParams(window.location.hash.slice(1)).get("access_token"), []);
  const linkError = !token ? "This recovery link is incomplete or expired. Request a new password-reset email and open the newest message." : "";
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(""); if (!token) { setError(linkError); return; } if (password.trim().length < 8) { setError("Use at least 8 characters for the new password, then try again."); return; } setSaving(true); try { await updatePasswordFromRecovery(token, password); setMessage("Password updated successfully. You can now sign in to FIR Saathi."); } catch (caught) { const source = caught instanceof Error ? caught.message : "Password update could not be completed."; setError(/network|fetch|timeout/i.test(source) ? "We could not reach the account service. Check your connection and try again." : source); } finally { setSaving(false); } };
  return <FirSaathiShell compact><main className="app-real-surface grid min-h-[calc(100vh-144px)] place-items-center px-5 py-10"><section className="w-full max-w-md rounded-2xl border border-[#102643]/10 bg-white p-7 text-center shadow-[0_18px_45px_rgba(12,32,57,.08)]"><span className="mx-auto grid h-11 w-11 place-items-center rounded-full bg-[#fff0e8] text-[#c64e19]"><KeyRound className="h-5 w-5" /></span><h1 className="mt-4 text-2xl font-bold text-[#102643]">Set a new password</h1><p className="mt-2 text-sm leading-6 text-slate-600">Choose a new FIR Saathi account password. The reset link can be used only once.</p>{message ? <div className="mt-5 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800"><CheckCircle2 className="mr-1 inline h-4 w-4" /> {message}<Link href="/officer" className="focus-ring mt-3 block font-bold underline underline-offset-4">Return to sign-in</Link></div> : <form onSubmit={submit} className="mt-5 space-y-3 text-left" aria-busy={saving}><label className="block text-xs font-bold text-[#102643]">New password<input required disabled={saving || !token} type="password" minLength={8} value={password} onChange={(event) => setPassword(event.target.value)} className="focus-ring mt-1.5 h-11 w-full rounded-xl border border-[#102643]/15 px-3 text-sm disabled:opacity-60" placeholder="At least 8 characters" autoComplete="new-password" /></label><p className="text-xs leading-5 text-slate-500">Use a unique password you do not reuse elsewhere.</p><button type="submit" disabled={saving || !token} className="focus-ring inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#102643] px-4 py-3 text-sm font-bold text-white disabled:opacity-60">{saving && <Loader2 className="h-4 w-4 animate-spin" />}{saving ? "Updating password…" : "Save new password"}</button></form>}{saving && <AuthFeedback kind="loading" message="Updating your password securely…" />}{linkError && !message && <><AuthFeedback kind="error" message={linkError} /><Link href="/officer" className="focus-ring mt-4 inline-block text-xs font-bold text-[#102643] underline underline-offset-4">Request another reset link</Link></>}{error && <AuthFeedback kind="error" message={error} />}</section></main></FirSaathiShell>;
}
