import { ExternalLink, FileSearch, Quote, Scale, ShieldAlert } from "lucide-react";
import type { BnsSuggestion, StructuredDraft } from "../../../shared/firSaathi";

type ReviewField = {
  id: string;
  fieldKey: string;
  label: string;
  value: string;
  source: "source_statement" | "officer_correction" | "assistant_draft" | "citizen_context";
};

function badge(suggestion: BnsSuggestion) {
  if (suggestion.suitability === "possible_match") return "bg-amber-300/20 text-amber-100";
  if (suggestion.suitability === "needs_officer_assessment") return "bg-slate-300/15 text-slate-200";
  return "bg-slate-300/15 text-slate-200";
}

export function BnsReviewPanel({ suggestions }: { suggestions: BnsSuggestion[] }) {
  return <section className="rounded-2xl border border-[#102643]/10 bg-[#102643] p-5 text-white"><div className="flex items-center gap-2"><Scale className="h-4 w-4 text-[#f48a51]" /><p className="text-xs font-bold uppercase tracking-[0.15em] text-slate-300">BNS review aids</p></div><p className="mt-2 text-xs leading-5 text-slate-400">Source-linked possibilities only. They do not determine a legal section, charge, or FIR.</p><div className="mt-4 space-y-3">{suggestions.map((suggestion) => { const sourceQuotes = Array.isArray(suggestion.sourceQuotes) ? suggestion.sourceQuotes : []; const missingFactors = Array.isArray(suggestion.missingFactors) ? suggestion.missingFactors : ["This earlier draft has no stored evidence map. Reassess from the source record."]; const suitability = suggestion.suitability ?? "officer_review"; return <article key={suggestion.sectionCode} className="rounded-xl bg-white/[0.08] p-3"><div className="flex flex-wrap items-start justify-between gap-2"><p className="text-sm font-bold">{suggestion.sectionCode} · {suggestion.title}</p><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${badge({ ...suggestion, suitability })}`}>{suitability.replaceAll("_", " ").toUpperCase()}</span></div><p className="mt-2 text-xs leading-5 text-slate-300">{suggestion.rationale}</p>{sourceQuotes.length > 0 && <div className="mt-3"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400">Exact source excerpts</p>{sourceQuotes.map((quote) => <blockquote key={quote} className="mt-1.5 flex gap-2 border-l border-[#f48a51] pl-2 text-xs leading-5 text-slate-200"><Quote className="mt-0.5 h-3 w-3 shrink-0 text-[#f48a51]" />{quote}</blockquote>)}</div>}{missingFactors.length > 0 && <div className="mt-3 rounded-lg bg-black/15 p-2.5"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400">Still needs assessment</p><ul className="mt-1 space-y-1 text-xs leading-5 text-slate-300">{missingFactors.map((factor) => <li key={factor}>• {factor}</li>)}</ul></div>}{suggestion.sourceUrl && <a href={suggestion.sourceUrl} target="_blank" rel="noreferrer" className="focus-ring mt-3 inline-flex items-center gap-1 text-[11px] font-bold text-[#ffd5c0] hover:text-white">Official source <ExternalLink className="h-3 w-3" /></a>}</article>; })}</div><div className="mt-4 flex gap-2 rounded-xl border border-[#f48a51]/20 bg-[#c64e19]/10 p-3 text-[11px] leading-5 text-[#ffd5c0]"><ShieldAlert className="mt-0.5 h-3.5 w-3.5 shrink-0" />If no source-linked card is suitable, the safe outcome is officer review required.</div></section>;
}

export function ReviewBrief({ sourceTranscript, fields, draft, dark }: { sourceTranscript: string; fields: ReviewField[]; draft: StructuredDraft; dark: boolean }) {
  const citizenContext = fields.filter((field) => field.source === "citizen_context");
  const transcriptNotes = citizenContext.filter((field) => field.fieldKey.startsWith("transcript_correction_"));
  const additionalContext = citizenContext.filter((field) => !field.fieldKey.startsWith("transcript_correction_"));
  const sourceFields = fields.filter((field) => field.source === "source_statement");
  const card = dark ? "border-white/10 bg-white/[0.055] text-slate-100" : "border-[#102643]/10 bg-white text-[#102643]";
  const muted = dark ? "text-slate-400" : "text-slate-600";
  const lane = dark ? "border-white/10 bg-black/15" : "border-[#102643]/10 bg-[#fbfaf6]";
  return <section className={`rounded-2xl border p-5 ${card}`}><div className="flex items-center gap-2"><FileSearch className="h-4 w-4 text-[#f48a51]" /><p className="text-xs font-bold uppercase tracking-[0.15em]">Constable review workspace</p></div><p className={`mt-2 text-xs leading-5 ${muted}`}>Keep the record in three lanes: what the citizen originally said, any separately supplied context, and the human decision still required.</p><div className="mt-4 grid gap-3 text-xs leading-5"><section className={`rounded-xl border p-3 ${lane}`}><p className="font-bold">1. Source record — locked</p><p className={`mt-1 line-clamp-3 ${muted}`}>{sourceTranscript}</p><ul className={`mt-3 space-y-1 ${muted}`}>{sourceFields.length ? sourceFields.map((field) => <li key={field.id}><b>{field.label}:</b> “{field.value}”</li>) : <li>No exact excerpt was safely extracted.</li>}</ul></section><section className={`rounded-xl border p-3 ${lane}`}><p className="font-bold">2. Citizen additions — separate</p><ul className={`mt-2 space-y-1 ${muted}`}>{additionalContext.length ? additionalContext.map((field) => <li key={field.id}><b>{field.label}:</b> {field.value}</li>) : <li>No additional context was supplied.</li>}</ul>{transcriptNotes.length > 0 && <div className="mt-3 border-t border-current/10 pt-3"><p className="font-bold">Timestamped transcript notes</p><ul className={`mt-1 space-y-1 ${muted}`}>{transcriptNotes.map((field) => <li key={field.id}>{field.value}</li>)}</ul></div>}</section><section className={`rounded-xl border p-3 ${lane}`}><p className="font-bold">3. Human decision — required</p><ul className={`mt-2 space-y-1 ${muted}`}>{draft.followUpQuestions.length ? draft.followUpQuestions.map((question) => <li key={question}>• {question}</li>) : <li>No AI follow-up question was produced; independently verify the source and evidence.</li>}</ul><p className="mt-3 font-semibold text-[#c64e19]">The constable decides whether to verify, correct a working field, or return for clarification. No AI output decides the outcome.</p></section></div></section>;
}
