import { ArrowRightLeft, Languages, Loader2, ShieldAlert } from "lucide-react";

type Translation = { englishAid: string; backTranslation: string; uncertaintyNote: string };

export default function ReviewerTranslationAid({ translation, pending, onGenerate, dark = false }: { translation?: Translation; pending: boolean; onGenerate: () => void; dark?: boolean }) {
  const card = dark ? "border-sky-300/20 bg-sky-300/[0.07] text-sky-50" : "border-sky-800/15 bg-sky-50 text-[#102643]";
  const muted = dark ? "text-sky-100/70" : "text-slate-600";
  return <section className={`rounded-2xl border p-5 ${card}`}><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-2"><Languages className="mt-0.5 h-4 w-4 shrink-0 text-sky-700 dark:text-sky-200" /><div><p className="text-xs font-bold uppercase tracking-[0.15em]">Reviewer translation aid</p><p className={`mt-2 text-xs leading-5 ${muted}`}>Generated only for this reviewer session. It is non-authoritative and never replaces the source record.</p></div></div>{!translation && <button type="button" disabled={pending} onClick={onGenerate} className="focus-ring inline-flex min-h-9 items-center gap-1.5 rounded-lg border border-sky-700/25 bg-white px-3 text-xs font-bold text-sky-900 disabled:opacity-50">{pending ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <ArrowRightLeft className="h-3.5 w-3.5" />}{pending ? "Preparing aid" : "Generate aid"}</button>}</div>{translation && <div className="mt-4 space-y-3"><div className={`rounded-xl p-3 ${dark ? "bg-black/15" : "bg-white"}`}><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-sky-700 dark:text-sky-200">English reviewer aid</p><p className="mt-2 text-sm leading-6">{translation.englishAid}</p></div><div className={`rounded-xl p-3 ${dark ? "bg-black/15" : "bg-white"}`}><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-sky-700 dark:text-sky-200">Back-translation check</p><p className="mt-2 text-sm leading-6">{translation.backTranslation}</p></div><p className={`flex gap-2 text-xs leading-5 ${muted}`}><ShieldAlert className="mt-0.5 h-3.5 w-3.5 shrink-0 text-sky-700 dark:text-sky-200" />{translation.uncertaintyNote || "Compare both aids against the immutable original before acting."}</p></div>}</section>;
}
